version: "3"
services:
  spring:
    image: openjdk:8-jre-slim
    command: "/bin/bash -c \"cp -R /distributions/* /runtime; tar -xf solideo-www-spring-boot.tar --directory ./ --strip-components=1; bash -x ./bin/solideo-www-spring\""
    working_dir: "/runtime"
    environment:
        SOLIDEO_WWW_SPRING_OPTS: "-Xmx512m -Djava.security.egd=file:/dev/./urandom -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"

    deploy:
      replicas: 1
      # resources: #Java 8 JVM does not respect these limits. It's better to use -XmX options
      #  limits:
      #    cpus: "0.3"
      #    memory: 500M
      restart_policy:
        condition: always
    ports:
      - "8080:8080"
    networks:
      - webnet
    volumes: 
      - "./build/distributions:/distributions:ro"

networks:
  webnet:
      
volumes:
    gradlehome2:
      
##########
## TODO ##
##########
#
# ~