version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: openjdk:8-jre-slim
    command: "/bin/bash -c \"cp -R /distributions/* /runtime; tar -xf solideo-www-spring-boot.tar --directory ./ --strip-components=1; bash -x ./bin/solideo-www-spring\""
    container_name: "solideo-www-spring"
    working_dir: "/runtime"
    environment:
        SOLIDEO_WWW_SPRING_OPTS: "-Xmx512m -Djava.security.egd=file:/dev/./urandom -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"

    #deploy:
    #  replicas: 1
    #  resources:
    #    limits:
    #      cpus: "0.3"
    #      memory: 500M
    #  restart_policy:
    #    condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
    volumes: 
      - "./build/distributions:/distributions:ro"

networks:
  webnet:
      
volumes:
    gradlehome2:
      
##########
## TODO ##
##########
#
# ~