#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" #https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within

echo "Usage: $0 [build] [start|stop|restart]"

SOLIDEO_RUN_OPTS=""
export SD_GRADLE_OPTIONS=""

sd_build="false"
sd_start="false"
sd_stop="false"
sd_restart="false"
sd_enable_hook="false"
sd_disable_hook="false"

sd_daemon="false" 
sd_build_scan="false"

while test -n "$1"; do
  case "$1" in
   build)
      sd_build="true"
      shift
      ;;
   start)
      sd_start="true"
      shift
      ;;
   stop)
      sd_stop="true"
      shift
      ;;
   restart)
      sd_restart="true"
      shift
      ;;
   enable-hook)
      sd_enable_hook="true"
      shift
      ;;
   disable-hook)
      sd_disable_hook="true"
      shift
      ;;
   --daemon|-d)
      sd_daemon="true"
      shift
      ;;
   --scan|-s)
      sd_build_scan="true"
      shift
      ;;
   *) 
      echo "Usage: $0 [build] [start|stop|restart]"
      exit 1
  esac
done

if [ "$sd_daemon" == "true" ]; then
  SOLIDEO_RUN_OPTS="-d"
fi

if [ "$sd_build_scan" == "true" ]; then
  export SD_GRADLE_OPTIONS="--scan"
fi

if [ "$sd_build" == "true" ]; then
  echo ""
  echo "Building solideo-www-spring"
  "$DIR/build.sh"
fi

if [ "$sd_restart" == "true" ]; then
  echo ""
  echo "Starting/restarting solideo-www-spring (with --force-recreate)"
  docker-compose -f "$DIR/docker-compose.yml" up $SOLIDEO_RUN_OPTS --force-recreate

elif [ "$sd_start" == "true" ]; then
  echo ""
  echo "Starting/restarting solideo-www-spring (with --force-recreate)"
  docker-compose -f "$DIR/docker-compose.yml" up $SOLIDEO_RUN_OPTS --force-recreate

elif [ "$sd_stop" == "true" ]; then
  echo ""
  echo "Stopping solideo-www-spring"
  docker-compose -f "$DIR/docker-compose.yml" stop
fi


if [ "$sd_enable_hook" == "true" ]; then
  echo ""
  echo "Copying post-merge.git.hook to .git/hooks"
  cp "$DIR/post-merge.git.hook" "$DIR/.git/hooks/post-merge"
  chmod a+x "$DIR/.git/hooks/post-merge"

elif [ "$sd_disable_hook" == "true" ]; then
  echo ""
  echo "Removing .git/hooks/post-merge"
  rm "$DIR/.git/hooks/post-merge"
fi
