package pl.solideo.www;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import pl.solideo.www.App;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        assertTrue(true);
    }
}
